name: 🐛 Bug Report
description: Something is wrong with React Router.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Do you need some help?
        ======================
        The issue tracker is meant for bug reports only. This isn't the best
        place for support or usage questions. Questions here don't have as much
        visibility as they do elsewhere. Before you ask a question, here are
        some resources to get help first:

        - Read the docs: https://reactrouter.com
        - Check out the list of frequently asked questions: https://reactrouter.com/start/faq
        - Explore examples: https://reactrouter.com/start/examples
        - Ask in chat: https://rmx.as/discord
        - Look for/ask questions on Stack Overflow: https://stackoverflow.com/questions/tagged/react-router

        ### Test Case Starters:

        * (Using `<RouterProvider>`)[https://stackblitz.com/github/remix-run/react-router/tree/main/examples/data-router?file=src/App.tsx]
        * (Using `<BrowserRouter>`)[https://stackblitz.com/github/remix-run/react-router/tree/main/examples/basic?file=src/App.tsx]
  - type: input
    attributes:
      label: What version of React Router are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
