name: 🧪 Test

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version-file: ".nvmrc"

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 🏗 Build
        run: yarn build

      - name: 🧪 Run tests
        run: yarn test

      - name: Check bundle size
        run: yarn size
